### ISSUE TITLE
Getting Null Pointer exception when starting the server.

### ISSUE THREAD

**Issue by shagihan** [wso2/carbon-device-mgt#1247]
**Description:**
When starting the the server getting the following error.

`Exception in thread "Thread-32" java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Integer.java:542)
at java.lang.Integer.parseInt(Integer.java:615)
at org.wso2.carbon.apimgt.integration.client.util.Utils$1.select(Utils.java:111)
at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.java:117)
at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.java:61)
at okhttp3.internal.connection.StreamAllocation.<init>(StreamAllocation.java:89)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:107)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
at okhttp3.RealCall.execute(RealCall.java:69)
at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:157)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
at com.sun.proxy.$Proxy26.register(Unknown Source)
at org.wso2.carbon.apimgt.integration.client.OAuthRequestInterceptor.apply(OAuthRequestInterceptor.java:86)
at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:158)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:88)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
at com.sun.proxy.$Proxy40.apisGet(Unknown Source)
at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherServiceImpl.publishAPI(APIPublisherServiceImpl.java:53)
at org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler.publishAPIs(APIPublisherStartupHandler.java:97)`

**Suggested Labels:**
WSO2IOT-3.1.0,IOT

**Affected Product Version:**
WSO2IOT-3.1.0

**Steps to reproduce:**
* Get the latest WUM update of wso2iot server 3.1.0.
* Start the server.

**Related Issues:**

**Comment by rasika** [comment]
Please move this issue into product repo.

**Comment by shagihan** [comment]
Fix has been provided.
