### ISSUE TITLE
Currently enrolled user incorrectly selected

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/carbon-device-mgt#727]
This issue triggers when the same device is enrolled to different users. When the device tries to get pending operations to execute, it triggers an exception and it states that user doesn't have authorization for accessing the device.

User 'xyz@xyz' is not authorized to access the 'abc’ device, which carries the identifier 'x' at org.wso2.carbon.device.mgt.core.operation.mgt.OperationManagerImpl.getNextPendingOperation(OperationManagerImpl.java:423) at org.wso2.carbon.device.mgt.core.service.DeviceManagementProviderServiceImpl.getNextPendingOperation(DeviceManagementProviderServiceImpl.java:1125)

**Comment by lasanthaDLPDS** [comment]
Fixed in #723
